version: '3'

services: 
  db: 
      image: postgres:14.3
      restart: always
      ports: 
        - "6433:5432"
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME} 
        TZ: ${DB_TZ}
      container_name: emunaDB
      volumes:
        - ./postgres:/var/lib/postgresql/data
        - ./local-persistent:/var/lib/postgresql/data
